name: Maintenance CI

on:
  push:
    branches:
      - 'maintenance'
  pull_request:
    branches:
      - 'maintenance'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v4

    - name: Restore Packages
      run: nuget restore SSMSExecutor.sln

    - name: Build Solution
      run: msbuild.exe SSMSExecutor.sln /property:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
